name: Auto Approve Pull Requests

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto-Approve
        uses: hmarr/auto-approve-action@v4
