name: Lint Markdown Files

on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run markdownlint
        uses: avtodev/markdown-lint@v1
        with:
          args: './**/*.md'
